[package]
name = "wordle-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
smallvec = "1.8.0"
itertools = "0.10.3"
rand = "0.8.4"
rayon = "1.5.1"
dashmap = "5.0.0"

[profile.release]
opt-level = 3
overflow-checks = false
lto = true
debug-assertions = false
